on:
  - push

name: ci

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: go vet -v ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: --disable unused

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ~1.23
    - id: go-version
      run: echo "version-used=$(go env GOVERSION)" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Cache Dependencies
      uses: actions/cache@v4
      id: go-cache
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/go/bin
        key: ${{ runner.os }}_${{ runner.arch }}-${{ steps.go-version.outputs.version-used }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}_${{ runner.arch }}-${{ steps.go-version.outputs.version-used }}-build-
    - name: Install Go dependencies
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Generate test files
      run: go generate ./...
    - name: Run tests
      run: go test ./... -v -cover -coverprofile=gocoverage.txt -covermode=atomic
    - name: Display Coverage
      run: go tool cover -func=gocoverage.txt
    - name: At Least 80% Coverage
      run: |
        go tool cover -func=gocoverage.txt | \
          awk '/^total/ { sub(/%/, ""); if ($3 < 80.0) { exit 1 } else { exit 0 } }'

  # build:
  #   name: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v4
  #   - name: Setup Go
  #     uses: actions/setup-go@v5
  #     with:
  #       go-version: ~1.23
